### PR TITLE
2.0.0 qnx

### PR DESCRIPTION
**Pull request by pablorcum**
Fixed QNX compilation.

### CODE REVIEW

**Review by DuboisNicolasAirbus — COMMENTED** [review]
.gitignore shall only contain files are explicitly generated. Files like '_build*'  are not specified in CmakeList, this is your naming choice.

**Review by DuboisNicolasAirbus — COMMENTED** [review]
I trust you for QNX build and I will pick your fixes.
I keep the QNX toochain as an example.

**Review by DuboisNicolasAirbus — COMMENTED** [review]
You have added <sys/select.h> to ed247_internal.h. This file will be removed at the end. Which objects/function need this header ? (To put the include at the right place)

**Comment by pablorcum** [comment]
Yes, the header <sys/select.h> is required.

**Review by DuboisNicolasAirbus — COMMENTED** [review]
<sys/select.h>: which object/function need this header ? The file ed247_internals.h will be removed at the end.

**Review by DuboisNicolasAirbus — COMMENTED** [review]
Instead of using cmake options, that force to re-run cmake and may rebuild all, I use different targets. I this the existing ones can fit your needs:
- all (default)
- ed247 : build only the library
- tests : build tests (and library)
- examples / utils
- doc
- ...

**Review by DuboisNicolasAirbus — COMMENTED** [review]
CMAKE_SKIP_RPATH: I've put this option in the toolchain.

**Comment by pablorcum** [comment]
Please see below the compiler error if <sys/select.h> is not included.
```
[  8%] Building CXX object src/ed247/CMakeFiles/ed247_objects.dir/ed247_channel.cpp.o
In file included from C:/Users/promero/git_work/Utilities/ED247_LIBRARY_my/src/ed247/ed247_channel.h:30,
                 from C:/Users/promero/git_work/Utilities/ED247_LIBRARY_my/src/ed247/ed247_channel.cpp:24:
C:/Users/promero/git_work/Utilities/ED247_LIBRARY_my/src/ed247/ed247_cominterface.h:283:21: error: 'fd_set' does not name a type; did you mean 'fdopen'?
```

**Review by DuboisNicolasAirbus — COMMENTED** [review]
You have removed SimulinkLogger from the build. Is this useless ? Shall we remove other references ? (find_package & code in logger)
Note: with the previous code, if you keep SimulinkLogger_INCLUDE_DIR empty, it will also be diabled.

**Comment by pablorcum** [comment]
I haven't removed it, it is still functional for SLRT builds. I have just simplified the way of adding the required path for the user replacing the very long path with the MATLAB root directory instead (MATLAB_ROOT_DIR) as shown below.

`find_path(SimulinkLogger_INCLUDE_DIR "Logger.hpp" HINTS ${MATLAB_ROOT_DIR}"/toolbox/slrealtime/target/kernel/dist/include")
`

**Comment by DuboisNicolasAirbus** [comment]
I've see that. I prefer to set SimulinkLogger_INCLUDE_DIR in QNX toolchain (see comments you have removed in [dc01536](https://github.com/airbus/ED247_LIBRARY/pull/27/commits/dc0153658a8ea1302c417bf2165b1ba7deafc408))
But you have also removed SimulinkLogger from the target. So it is not used...

**Comment by DuboisNicolasAirbus** [comment]
I've merged a part of your pull request in the master.

**Pull request closed without merging**
